config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'home' => 'static_pages#home'
  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :microposts
  resources :users
  root 'static_pages#home'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	validates :content, presence: true, length: { maximum: 140 }
	validates :user_id, presence: true
	default_scope -> { order(created_at: :desc) }
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
	validates :name, presence: true, length: { maximum: 50 }
	validates :email, presence: true, length: { maximum: 255 },
               format: { with: VALID_EMAIL_REGEX },
               uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, allow_blank: true
    
	has_secure_password
  has_many :microposts, dependent: :destroy

	# Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  def index
    @microposts = Micropost.all
  end

  def show
  end

  def new
    @micropost = Micropost.new
  end

  def edit
  end

  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
  	log_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :admin_user, only: [:index, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:show, :edit, :update]
  before_action :admin_user,     only: [:index]

  def index
    #@users = User.all
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "MicroBlog"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
  
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="row">
    <div class="small-3 small-centered columns">Copyright 2015</div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<%# navigation header styled for Zurb Foundation 5 %>

<header class="header">
<div class="row fullWidth">
  <nav class="top-bar top-bar2" role="navigation" data-options="sticky_on: large">
	  <ul class="title-area">
	    <li class="name">
	      <h1><a href="#" class="navtop_link"><%= image_tag("mblog.png", :alt => "rss feed") %> <%= t('appname') %></a></h1>
	    </li>
	     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
	    <li class="toggle-topbar menu-icon"><a href="#"><span><%= t('menu') %></span></a></li>
	  </ul>

	  <section class="top-bar-section">

	    <!-- Right Nav Section -->
	    <ul class="right">

	      <% if current_user %>
	      	<li><%= link_to current_user.name, current_user, class: "navtop_link" %></li></li>
	      	<li><%= link_to t('logout'), logout_path, method: "delete", class: "navtop_link" %></li>
	      <% else %>
	      	<li><%= link_to t('login'), login_path, class: "navtop_link" %></li>
	      <% end %>
	      <li>"  "</li>

	    </ul>

	    <!-- Left Nav Section -->
	    <ul class="left">
	      <li><%= link_to t('home'), root_path, class: "navtop_link" %></li>
		    <li><%= link_to t('posts'), microposts_path, class: "navtop_link" %></li>
		     <% if current_user %>
			     <% if current_user.admin? %>
			    	<li><%= link_to t('users'), users_path, class: "navtop_link" %></li>
			    <% end %>
			 <% end %>
	    </ul>

	  </section>
	</nav>
</div>
</header>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation_left.html.erb
<%# add left navigation links to this file %>

<div class="sidebar">
	<nav>
		<ul class="side-nav">
	  	<li class="heading">Setup</li>
			<li><%= link_to 'Home', home_path %></li>
		</ul>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= yield(:title)  %> | MicroBlog</title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Mblog" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body>
  
    <%= render 'layouts/header' %>

		<div class="row fullWidth">
		  <div class="medium-2 columns" style="background-color:#CCCCCC">
          <%= render 'layouts/navigation_left' %>
      </div>

		  <div class="medium-10 columns">
		  	<main role="main">
		       <%= render 'layouts/messages' %>
		       <%= yield %>
		    </main>
		  </div>
      
      <div class="medium-10 columns">
        <%= render 'layouts/footer' %>
      </div>
		</div>

  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<li id="<%= micropost.id %>">
  
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<h1>MicroBlog</h1>
<p>
  This is the home page for the
  <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

<%= link_to 'Sign Up', signup_path, class: "button button_link" %>
<p>Already have an account? <%= link_to "Login", login_path, class: "text_link" %></p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Save", class: "button tiny radius" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit Account") %>
<h3><%= yield(:title) %></h3>

<%= render 'form' %>

<%= link_to 'Show', @user, class: "text_link" %> |
<%= link_to 'Back', users_path, class: "text_link" %>

app/views/users/index.html.erb
<% provide(:title, "Users") %>
<h3><%= yield(:title) %></h3>

<div class="row">
  <div class="small-4 large-centered columns">
    <%= will_paginate @collection, renderer: FoundationPagination::Rails %>
  </div>
</div>

<table width="100%">
  <thead>
    <tr>
      <th width="40%">Name</th>
      <th width="25%">Email</th>
      <th width="10%">Admin</th>
      <th colspan="15%">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <% if user.admin %>
            <span class="alert round radius label"><%= user.admin %></span>
          <% else %>
            <span class="success round radius label"><%= user.admin %></span>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td>
          <% if current_user.admin? && !current_user?(user) %>
            <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, "Create Account") %>
<h3><%= yield(:title) %></h3>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% provide(:title, "Account") %>
<h3><%= yield(:title) %>: <%= @user.name %></h3>

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="small-3 columns">
 
    <table  width="50%">
      <tbody>
        <tr>
          <td><strong>Name</strong></td>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <td><strong>Email</strong></td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td><strong>Admin?</strong></td>
          <td>
            <% if @user.admin %>
              <span class="alert round radius label"><%= @user.admin %></span>
            <% else %>
              <span class="success round radius label"><%= @user.admin %></span>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>

    <%= link_to 'Edit', edit_user_path(@user), class: "text_link" %> |
    <%= link_to 'Back', users_path, class: "text_link" %>

  </div>

<div class="small-9 columns">
  <div class="col-md-8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>